trigger:
- feature-ms-pabloSepulveda-mensaje

jobs:
- job: MicroservicioSpringPipeline
  displayName: 'microservicio spring pipeline'
  pool:
   vmImage: ubuntu-latest
  steps:
#  - script: |
#      git fetch --unshallow
#    displayName: 'convert to non-shallow clone' 
  - task: Maven@3
    displayName: 'Build'
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: 1.11
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'clean test'
  - task: PublishCodeCoverageResults@1
    displayName: 'Publish code coverage results (JaCoCo)'
    inputs:
        codeCoverageTool: 'JaCoCo'
        summaryFileLocation: '$(System.DefaultWorkingDirectory)/target/site/jacoco/jacoco.xml'
        pathToSources: '$(System.DefaultWorkingDirectory)/src/main/java/'
        reportDirectory: '$(System.DefaultWorkingDirectory)/target/site/jacoco'
        failIfCoverageEmpty: true
  - task: SonarCloudPrepare@1
    displayName: 'SonarCloud Prepare'
    inputs:
      SonarCloud: 'DevOps Project'
      organization: 'psep'
      scannerMode: 'Other'
      projectKey: 'Psep_microservicio-spring'
      projectName: 'microservicio-spring'

  - task: Maven@3
    displayName: 'Code Review (SonarCloud)'
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: 1.11
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'clean package'
      sonarQubeRunAnalysis: true
  - task: Docker@2
    displayName: 'Docker Login'
    inputs:
      containerRegistry: 'Docker Hub Psep'
      command: 'login'
  - task: Docker@2
    displayName: 'Docker registry image'
    inputs:
      containerRegistry: 'Docker Hub Psep'
      repository: 'psep/testing-web-complete'
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'
#      tags: '$(Build.BuildId)'

- job: Deploy
  displayName: 'Deploy to Kubernetes'
  dependsOn: MicroservicioSpringPipeline
  pool: 'Default'
  steps:
  - task: Bash@3
    displayName: 'Tag image replace'
    inputs:
      targetType: 'inline'
      script: |
        cat app-deployment.yaml
        echo "Cambiando tag de deployment"
        sed -i "s|_tag_|$(Build.BuildId)|g" app-deployment.yaml
        cat app-deployment.yaml
  - task: Kubernetes@1
    displayName: 'Deploy pod'
    inputs:
      connectionType: 'None'
      command: 'apply'
      arguments: '-f app-deployment.yaml'
  - task: Kubernetes@1
    displayName: 'Apply app service'
    inputs:
      connectionType: 'None'
      command: 'apply'
      arguments: '-f app-service.yaml'

  