trigger:
- feature-ms-pabloSepulveda-mensaje

jobs:
- job: Pipeline
  displayName: 'Pipeline'
  pool:
   vmImage: ubuntu-latest
  steps:
  - script: |
      git fetch --unshallow
    displayName: 'convert to non-shallow clone' 
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: 1.11
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'clean test'
  - task: PublishCodeCoverageResults@1
    inputs:
        codeCoverageTool: 'JaCoCo'
        summaryFileLocation: '$(System.DefaultWorkingDirectory)/target/site/jacoco/jacoco.xml'
        pathToSources: '$(System.DefaultWorkingDirectory)/src/main/java/'
        reportDirectory: '$(System.DefaultWorkingDirectory)/target/site/jacoco'
        failIfCoverageEmpty: true
  - task: SonarCloudPrepare@1
    displayName: 'SonarCloud Prepare'
    inputs:
      SonarCloud: 'DevOps Project'
      organization: 'psep'
      scannerMode: 'Other'
      projectKey: 'Psep_microservicio-spring'
      projectName: 'microservicio-spring'

  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: 1.11
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'clean package'
      sonarQubeRunAnalysis: true
  - task: Docker@2
    inputs:
      containerRegistry: 'Docker Hub Psep'
      command: 'login'
  - task: Docker@2
    inputs:
      containerRegistry: 'Docker Hub Psep'
      repository: 'psep/testing-web-complete'
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'