trigger:
- feature-ms-pabloSepulveda-mensaje

jobs:
- job: BuildAndPublish
  displayName: 'Build and publish'
  pool:
   vmImage: ubuntu-latest
  steps:
  - task: Maven@3
    displayName: 'Build'
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: 1.11
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'clean test'
  - task: PublishCodeCoverageResults@1
    displayName: 'Publish code coverage results (JaCoCo)'
    inputs:
        codeCoverageTool: 'JaCoCo'
        summaryFileLocation: '$(System.DefaultWorkingDirectory)/target/site/jacoco/jacoco.xml'
        pathToSources: '$(System.DefaultWorkingDirectory)/src/main/java/'
        reportDirectory: '$(System.DefaultWorkingDirectory)/target/site/jacoco'
        failIfCoverageEmpty: true

  - task: Bash@3
    displayName: 'Validate Coverage 85%'
    inputs:
      targetType: 'inline'
      script: |
        jacocoXmlPath='$(System.DefaultWorkingDirectory)/target/site/jacoco/jacoco.xml'
        threshold=85

        coverage=$(grep -oP 'covered="\K[0-9]+' $jacocoXmlPath)
        missed=$(grep -oP 'missed="\K[0-9]+' $jacocoXmlPath)

        coveragePercentage=$(bc -l <<< "scale=2; $coverage / ($coverage + $missed) * 100")

        if (( $(echo "$coveragePercentage >= $threshold" | bc -l) )); then
          echo "La cobertura ($coveragePercentage%) es mayor o igual a $threshold%"
        else
          echo "La cobertura ($coveragePercentage%) es menor a $threshold%"
          exit 1
        fi
  - task: SonarCloudPrepare@1
    displayName: 'SonarCloud Prepare'
    inputs:
      SonarCloud: 'DevOps Project'
      organization: 'psep'
      scannerMode: 'Other'
      projectKey: 'Psep_microservicio-spring'
      projectName: 'microservicio-spring'

  - task: Maven@3
    displayName: 'Code Review (SonarCloud)'
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: 1.11
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'package'
      sonarQubeRunAnalysis: true
  - task: sonarcloud-buildbreaker@2
    inputs:
      SonarCloud: 'DevOps Project'
      organization: 'psep'
  - task: Docker@2
    displayName: 'Docker Login'
    inputs:
      containerRegistry: 'Docker Hub Psep'
      command: 'login'
  - task: Docker@2
    displayName: 'Docker build and publish image'
    inputs:
      containerRegistry: 'Docker Hub Psep'
      repository: 'psep/testing-web-complete'
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'

- job: Deploy
  displayName: 'Deploy to Kubernetes and Test'
  dependsOn: BuildAndPublish
  pool: 'Default'
  steps:
  - task: Bash@3
    displayName: 'Tag image replace'
    inputs:
      targetType: 'inline'
      script: |
        cat k8s/app-deployment.yaml
        echo "Change tag image in deployment file"
        sed -i "s|_tag_|$(Build.BuildId)|g" k8s/app-deployment.yaml
        cat k8s/app-deployment.yaml
  - task: Kubernetes@1
    displayName: 'Deploy application'
    inputs:
      connectionType: 'None'
      command: 'apply'
      arguments: '-f k8s/app-deployment.yaml'
  - task: Kubernetes@1
    displayName: 'Apply app service'
    inputs:
      connectionType: 'None'
      command: 'apply'
      arguments: '-f k8s/app-service.yaml'
  - task: Bash@3
    displayName: 'Test with JMeter'
    inputs:
      targetType: 'inline'
      script: |
        /home/psep/labdevops/apache-jmeter-5.5/bin/jmeter -n -t jmeter/test.jmx -l jmeter/results.jtl
        cat jmeter/results.jtl