trigger:
- feature-ms-pabloSepulveda-mensaje

jobs:
- job: Build
  displayName: 'Build'
  pool:
   vmImage: ubuntu-latest
  steps:
  - script: |
      git fetch --unshallow
    displayName: 'convert to non-shallow clone' 
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'package'

  - task: PublishCodeCoverageResults@1
    inputs:
        codeCoverageTool: 'JaCoCo'
        summaryFileLocation: '$(System.DefaultWorkingDirectory)/target/site/jacoco/test/jacoco.xml'
        pathToSources: '$(System.DefaultWorkingDirectory)/src/main/java/'
        reportDirectory: '$(System.DefaultWorkingDirectory)/target/site/jacoco'
        failIfCoverageEmpty: true
